// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace NerdStore.BDD.Tests.Usuario
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class UsuRio_CadastroFeature : object, Xunit.IClassFixture<UsuRio_CadastroFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CadastroDeUsuario.feature"
#line hidden
        
        public UsuRio_CadastroFeature(UsuRio_CadastroFeature.FixtureData fixtureData, NerdStore_BDD_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Usuario", "Usu�rio - Cadastro", @"	Como um visitante da loja
	Eu desejo me cadastrar como usu�rio
	Para que eu possa realizar compras na loja


Cen�rio: Cadastro de usu�rio com sucesso
Dado Que o visitante est� acessando o site da loja
Quando Ele clicar em registrar
E Preencher os dados do formulario
	| Dados                |
	| Email                |
	| Senha                |
	| Confirma��o da Senha |
E Clicar no bot�o registrar
Ent�o Ele ser� redirecionado para a vitrine
E Uma sauda��o com seu e-mail ser� exibida no menu superior


Cen�rio: Cadastro com senha sem maiusculas
Dado Que o visitante est� acessando o site da loja
Quando Ele clicar em registrar
E Preencher os dados do formulario com uma senha sem maiusculas
		| Dados                |
		| E-mail               |
		| Senha                |
		| Confirma��o de senha |
E Clicar no bot�o registrar
Ent�o Ele receber� uma mensagem de erro que a senha precisa conter uma letra maiuscula

Cen�rio: Cadastro com senha sem caractere especial
Dado Que o visitante est� acessando o site da loja
Quando Ele clicar em registrar
E Preencher os dados do formulario com uma senha sem caractere especial
		| Dados                |
		| E-mail               |
		| Senha                |
		| Confirma��o de senha |
E Clicar no bot�o registrar
Ent�o Ele receber� uma mensagem de erro que a senha precisa conter um caractere especial", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                UsuRio_CadastroFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                UsuRio_CadastroFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
